### ISSUE TITLE
[Tracking] - Deneb Signing 

### ISSUE THREAD

**Issue by james-prysm** [ethereum/remote-signing-api#2]
Simple tracking for deneb support

- [x] deneb block signing
- [x] deneb blinded block signing
- [ ] ~~deneb blob sidecar signing~~
- [ ] ~~deneb blinded blob sidecar signing~~

**Comment by james-prysm** [comment]
blob signing is no longer needed

**Comment by james-prysm** [comment]
closing issue, everything should be supported.
